[firebase]
type = "service_account"
project_id = "bibliotecaprojeta-840dc"
private_key_id = "d43ff50ea055a0d7ff7bea66b102bf1acd41aa92"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC+/gMKVyeZ50z/4L+5WOQwE+4dEqNXCYyf/D8VpK1TRFguCVMC4DwXRKp/A6P0dex2thKw7O3Sc5RT
FrS/gzktdr5GrvW7Q38v2BAzCYwGMUXuAyhSZT8NNEMrGfpgrTM7qHOrn2/gGiY9NoMz6S+LWVfQaAEM1VnNe7QSRSZmPOEqISkciz+3fbnh9iw72ObHLtSsCR4GQlaP+
C09DuDexhMgJUoYXUZQnQrRiRQU8brXGzOBDjcXDNeLe1XP/R33Ec+I8+SJZTDFyxVPe4hKC57WiYE3B9rhUWvpAV3XRfR2t4fAU6UEzzweT5ObuO1QhmTXge/vCvZ9ay5
mfX4RAgMBAAECggEAVR3xDu+uh2lMqJBqAVk7QK3xJWXEA6sOz9Hj72pXkE9aGRIwu4xhW2FPtpFRxUW0n2cfR1gf2PWHecwZu2vo1Hkh7XBVtSIskY7yETzE+ZGF/7/K
fYX/povPD2thaSpnNcQp4KeKfU5KEmez6zOV671iZE+lgCmo/umNY8MLjO35s8+uT7zW8ZPH4eU6Zu9bHNcNhmFRDGZmNepTQxmrhYoJuhWpvBft9RFYz/mHQrVt0Z9+J
1dwmIM9yxo5kJaZtmCGYCdNvnVqHFIl3WF2oactsAgiuw5oorZK4nJ2vTqEiEhiRBa8tNoBzp1bj27UqNVucaw5rGMnWYXEnkOwrQKBgQDf9+iCwakEvSzPDAMmsz/vOG
LZ4LLUibMGPqV2aaANc6TlniCouDRS3G0DwF0Bm5+DuwhYFtTvouukoE7iLg6Bch7Kipds9v8wxGtawBTJWV6STVzc/u6s2wRQwGjy9MlgT9RkJyFM7ZxuxCiBwyLCSIxB
RpVuLzACHG5LB991SwKBgQDaTsHAUDchlPW0WK/5sMvJRJuy35yoXJTCnpu+JlVFNoId1/2jMS6xDxAZAZo814oCP1LnsjkjsViVF7eiZ4MCZTfEB7Lh4EqzZINJbOY7pd
nD3zje6rO1twEyHc+0pSNTm6fWwFdaEPyO9RBtmaH9xYLacoeXk+Z05PqyF6TskwKBgGy8ZYwmDbMZTUnwYQ9G84Fm9McnCmuZtusPOzH0MhqVzLcWQHDpja21CtBJcl43
eghwo6pw20zE4nb4xZOWHMDH8R8Qjlf+ywKYOi7DFtRyqTGKkc1Rj/soEj5KTCm4opQ57bn6LXa13b8BSVFGtfdxVXbTl/T4v+wmdX3EAr9lAoGBAL/h4aMr3omB6MVv/p
01rKlnyILc0VGarpax2qqz/tcrJgsdQi8il6vBVaDlK7C2svNuvWwx1s9snjPN+PaijSCZ3v5K1gx7nK05d7weH+/lwxbLKa2mFfdut3pZgauCSx69/jRgM2dS7uqotJvh
IeVwqadga5XrxfCRI1lONwRJAoGASoPU3ktSHKz2bVvBpDp5X9I9+nASXrzogjDuYy2Sv/bByYXjIfPCPonqeyWb9CDIDADBkqr3FBCKVTo+stKKkIMlGPosxyXMRBH+SZ
+vGvU25tVaIDDfxLBKlV+VGx8HaqXcX9xE7xB/Fa99PhZM+ggpdWHt61RhPDRGlWf4NVU=
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@bibliotecaprojeta-840dc.iam.gserviceaccount.com"
client_id = "117909562801074484077"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40bibliotecaprojeta-840dc.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
